### ISSUE TITLE
Bug: Error mit MM 2.0.0-alpha8

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_color#5]
nach Installation von
metamodels/attribute_color 	2.0.0-alpha1 bzw.
dev-master Referenz: 1c3af963

mit MM core 2.0.0-alpha8

auf Seite zum Anlegen eines Attributes

```
Warning: Invalid argument supplied for foreach() in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\meta-palettes\src\MetaPalettesBuilder.php on line 214

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\meta-palettes\src\MetaPalettesBuilder.php(214): __error(2, 'Invalid argumen...', 'C:\\Contao2Go\\ht...', 214, Array)
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\meta-palettes\src\MetaPalettesBuilder.php(91): Bit3\Contao\MetaPalettes\MetaPalettesBuilder->parsePalettes(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultPalettesDefinition), Object(ContaoCommunityAlliance\DcGeneral\Contao\Dca\Palette\LegacyPalettesParser), Array, Array, Array, Array)
#2 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DataDefinition\Builder\AbstractEventDrivenDataDefinitionBuilder.php(96): Bit3\Contao\MetaPalettes\MetaPalettesBuilder->build(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer), Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\DataDefinition\Builder\AbstractEventDrivenDataDefinitionBuilder::process(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func('Bit3\\Contao\\Met...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(392): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(336): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createContainer()
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(298): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createEnvironment()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(77): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_metamodel_at...', Array)
#11 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#12 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#13 {main}
```

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@zonky2 could you please have a final look at this and tell if your issue has been resolved?

**Comment by zonky2** [comment]
the failure is fixed but we have warnings

```Warning: unserialize() expects parameter 1 to be string, array given in composer\vendor\metamodels\attribute_color\src\MetaModels\Attribute\Color\Color.php on line 146```

https://github.com/MetaModels/attribute_color/blob/hotfix/2.0.0-alpha2/src/MetaModels/Attribute/Color/Color.php#L146

PR #7

**Comment by zonky2** [comment]
fixed with MM core alpha11
